# Generated by Django 3.0.7 on 2021-01-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='content',
            field=models.TextField(max_length=950),
        ),
    ]
