# Generated by Django 3.0.7 on 2021-01-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_auto_20210124_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
