# Generated by Django 3.0.7 on 2021-01-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_suggestion_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.EmailField(max_length=950),
        ),
    ]
