# Generated by Django 3.1.3 on 2020-11-09 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo_link', models.CharField(max_length=600)),
                ('city', models.CharField(max_length=20)),
                ('job', models.TextField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('date_register', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
